### ISSUE TITLE
Feature: Move svg image to /assets/img

### ISSUE THREAD

**Issue by inetbiz** [git-no/jekyll-breadcrumbs#11]
Can you recode this to place the image into the `/assets/img/` folder please?

**Comment by git-no** [comment]
This example is just one option.
Feel free to use any image type and store it where you like.

You just need to modify your style/css and point the html to your image location.
Instead of including the image itself include code which points to the image url or location.
Look here [https://jekyllrb.com/docs/includes/](https://jekyllrb.com/docs/includes/)

Drop the SVG code in the include file and enter your image tag. This should work, but haven't tested myself.
I appreciate you use the plugin but I am sorry, unfortunately I do not have time nor the money to support web development questions. Sorry, this jekyll-breadcrumb is free of charge and comes as it is :-)
